### ISSUE TITLE
More "Activity Points" Packages 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#209]
Hello :) 

I think it'll be nice, to have more Packages available for members when purchasing activity points

right now you can buy 10,20,30 or 40 I think it is

If the admin could change the number of points in a package and add as many as they want :)

for example

50,100,150,200,250,300 

:) I Hope this sparks the interest of Phpfox :)

**Comment by comemoreru** [comment]
Why is that? I don't think

**Comment by Lukey199223** [comment]
To Attract members to be more active on the site and earn the admin more income :)

**Comment by comemoreru** [comment]
too easy, I'm not sure)

**Comment by Lukey199223** [comment]
What ? :)

**Comment by Data66PF** [comment]
So you want a setting, where the points conversion settings are, for points denominations and then the admin can set it to amounts they want?

For viewing, this needs to be limited to a specific amount of packs to choose from due to responsive themes. I guess we could allow admins to choose 5 pack amounts via an input block (5 inputs) and then they can set how many can be purchased at once. Should we accept this next time we are looking.

**Comment by Lukey199223** [comment]
yes thats exactly it Donna :) , 
Ye I understand there needs to be a limit of packages , 

sorry for the late reply, didnt get an email :/

**Comment by prepperz** [comment]
There's definitely a need for this. Points are the most neglected and under utilized asset. It really can be the life blood of a site if it used properly. The points system and management definitely needs to focused on and expanded.

**Comment by neil96** [comment]
It's duplicate with #125
