### ISSUE TITLE
Comments on new line

### ISSUE THREAD

**Issue by optpf** [PHPfox-Official/phpfox-v4-feature-requests#22]
First, great idea opening this repo: you can track every feature request here in a very good way.

Actually there is no possibility to go on new line in comments and so many people, me included, think this should be possible.
The only way actually is to write externally and paste the text in the field. This is strange for a website that maybe wants to be big.
Data66 too said that this could be a good feature, because it is necessary in 90% of websites.
It is old-style the non-possibility to go on new line.

It could be enough adding a button to send the comment.
I'm saying a button because in mobile it's impossible do SHIFT + ENTER, so or we do like Facebook:
- SHIFT + ENTER on PC
- Button on mobile

Or we just place a button for both versions.

**Comment by Data66PF** [comment]
Please note that we said to only have one feature request per submission as each thing is totally different. Rather than me reject this right away, please change it to be only for the IM chat app and then open a new one for comments.

**Comment by optiroot** [comment]
I edited this for comments, as it is more needed than messages; even because I said that I don't use the new IM chat app, but the old-style messages system.

I'll open a new feature request for messages.

Sorry for the problem, I though that messages and comments could be related, as how I seen in the code they share so many parts (not the IM app).

**Comment by Data66PF** [comment]
the IM app replaced the pm messages when it is enabled but they are tied together in such a way that we would need to have it separated. Thanks for changing this. :) I'm sure it will be a popular one as will the pm message one if you submit one for that.

**Comment by Data66PF** [comment]
I like this idea as it's hard to write comments and read long ones if there is no submit button as we have to have run on comments that are hard to read because Enter submits it. IMO, it would be a better user experience to have a button. Will see what the team says and whether other clients also comment.

**Comment by optiroot** [comment]
Oh, I see. So you're right, it's better to keep them separated. :)

I opened the feature request about comments!

Yes, I think it is better to go on new line but the HTML and CSS for them should need to be re-done, because if you try to paste something you can see that the space you have to see the comment is really little: within about 30px you already see the scroll buttons at the right side of the comment.

Let's wait to see if other users need this and developers what say.

**Comment by neil96** [comment]
Dear @optpf ,

This feature is now available on phpFox 4.6.0.

Regards.
