### ISSUE TITLE
Support Rewrite URL for phpFox Apps

### ISSUE THREAD

**Issue by Phong-YouNet** [PHPfox-Official/phpfox-v4-feature-requests#247]
There is a table "phpfox_rewrite" and Rewrite URL is still working well with Modules on phpFox 4. But not with apps. 

Please support Rewrite URL for apps. Users like to update URLs of apps to  their favorite ones.

**Comment by PhpFoxJohnJr** [comment]
OMG I am about to go crazy...I have YouNet business directory.  If this #247 is implemented would it fix my current URL for the business directory?

https://mydomain.com/directory/detail/929/abc-restaurant/

I have spent weeks trying to figure out a work around.  I even asked stackoverflow and the main guy could not figure it out...

http://stackoverflow.com/questions/40206038/rewrite-url-with-just-company-name-with-current-htaccess-file/40206348#40206348

**Comment by neil96** [comment]
Hi Phong-YouNet,

This feature can be done in your own app. With route system, you can allow admin change the url in admincp.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Neal are you saying their is place to change the url in admincp.  I am hoping so as YouNet side has some awesome add-ons but who ever decided on the url format wasn't too bright.  The business directory url is horrible and way to long and I would understand since it is an old add-on but even their newest most popular theme has a searchable url and not a common url as well (mydomain.com/ynclean/landing...).  Why they decided to add such a stupid non common word like ynclean puzzles me unless it is there way of keeping track of their users.  Anyways any ideas would be helpful as you can see my business URL two comments above.
