### ISSUE TITLE
Better ad system

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-feature-requests#283]
Despite a promise for better ad system, everything is the same.

**We need:**
Notification for admin when new ad is pending.
Notification when ad has ended for admin and user.
view/click ad tracking that actually works.
**Manage Ads**;
Ability to edit ads. (photo, title, link, text)
Ability to re enable ads that are finished.
**Admin Control Panel**;
Ability to view ad in modal via admin panel.
Ability to edit ad via admin panel.
Ability to see who is the owner of ad.

**Comment by IsabellaJolie** [comment]
Hi djafrika,
Currently, we're focusing on some other features of Better Ads. However, your suggestion is so good and we will consider to implement it in next version of Better Ads. Thanks for your help

**Comment by one44123** [comment]
Ads under basic ads and advanced adds must be able to place on top of block above other blocks or between existing blocks for position and exposure.

**Comment by chena321** [comment]
Yes.  need very badly

**Comment by Lidercan** [comment]
and hide ads on index.visitor or any pages.

**Comment by IsabellaJolie** [comment]
Hi djafrika ,
We will add your improvements to our new version of Better Ads. However, some features will not added as following
1. Notification for admin when new ad is pending: admin can go to Dashboard page to view how many pending ads are there
2. Notification when ad has ended for admin: we could not do this feature because some sites has many admins to manage site. We should not send notification for all of them

The rest will be checked carefully if we can implement them.
Thanks a lot for your feedback

**Comment by heebeha** [comment]
Since the guest/visitor homepage on most themes is more of a landing page, the ads should never show there.  Has this been addressed/fixed in the latest version of Better Ads Version 4.1.2 , the most current version as of 8/1/2017

**Comment by heebeha** [comment]
![better ads on visitor homepage](https://user-images.githubusercontent.com/30631992/28837774-f8c8740e-76bb-11e7-9cfc-10f249bc1c97.png)
