### ISSUE TITLE
Allow IM Chat internally 

### ISSUE THREAD

**Issue by JOJOA1** [PHPfox-Official/phpfox-v4-feature-requests#509]
How about having an option of using IM App  by Node.js server, or internally  by using our servers bandwidth localhost

**Comment by neil96** [comment]
Hi @JOJOA1 ,

You can install and using nodejs in the same server with php server. Please read this [tutorial](https://docs.phpfox.com/display/FOX4MAN/Server+Setup+for+IM+Module) for more information.

Regards.

**Comment by erick260** [comment]
yea but your making some features like upload videos, IM app where we can only have them by other 3rd Party witch is not free, what is the point in paying for our servers, when we have to pay amazon to host our videos, and nodejs. This is why i suggested of making them where we can use our server, instead of having to use other 3rd Party

**Comment by JOJOA1** [comment]
yea but your making some features like upload videos, IM app where we can only have them by other 3rd Party witch is not free, what is the point in paying for our servers, when we have to pay amazon to host our videos, and nodejs. This is why i suggested of making them where we can use our server, instead of having to use other 3rd Party

**Comment by neil96** [comment]
Hi @JOJOA1 ,

Both Videos and IM are supported by phpFox. You can install in your VPS or dedicated without any 3rd-party services.

Regards.

**Comment by jonchelsowens16** [comment]
His
