### ISSUE TITLE
Add tax field to new 4.6 Ad Server.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-feature-requests#608]
I don't know what the new Ad Server for version of phpFox 4.6 will be called, but could you add a tax field to the new Ad Server so that taxes e.g. VAT, can be calculated and a total price be given for payment.

**Comment by jonchelsowens16** [comment]
On Feb 26, 2018 9:18 AM, "starplan" <notifications@github.com> wrote:

I don't know what the new Ad Server for version of phpFox 4.6 will be
called, but could you add a tax field to the new Ad Server so that taxes
e.g. VAT, can be calculated and a total price be given for payment.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/608>,
or mute the thread
