### ISSUE TITLE
We need to be able to sell our sites 

### ISSUE THREAD

**Issue by Lukey199223** [PHPfox-Official/phpfox-v4-feature-requests#628]
Hello :) Hope your all ok :) , 
sorry I havent posted in a while. I've been ill with a bard throat, 

I have a feature but its an add on to a feature request i' Have already posted and its been accepted, its for more power for admins on their website but I cant seem to find the post to add this too, so if someone could please add this to the "More power for admins" request, that would be much appreciated, thank you :) 

I think along with more power, we need to have the option to sell our websites or sell part of a website if the admin chooses, for instance, if an admin chooses to sell part of his/her website, they can type in the percentage of the website they want to sell and to who they're selling it too, I think this will give the admin A lot more power and movability in their website, I think with the admin having this power along side phpfox's updates etc, our websites would be unstoppable and gain a lot more power :)

**Comment by neil96** [comment]
Hi,

phpFox allows this. If you need more information, you can contact us via support ticket.

Regards.

**Comment by jonchelsowens16** [comment]
On Mar 23, 2018 11:50 AM, "Lukey199223" <notifications@github.com> wrote:

Hello :) Hope your all ok :) ,
sorry I havent posted in a while. I've been ill with a bard throat,

I have a feature but its an add on to a feature request i' Have already
posted and its been accepted, its for more power for admins on their
website but I cant seem to find the post to add this too, so if someone
could please add this to the "More power for admins" request, that would be
much appreciated, thank you :)

I think along with more power, we need to have the option to sell our
websites or sell part of a website if the admin chooses, for instance, if
an admin chooses to sell part of his/her website, they can type in the
percentage of the website they want to sell and to who they're selling it
too, I think this will give the admin A lot more power and movability in
their website, I think with the admin having this power along side phpfox's
updates etc, our websites would be unstoppable and gain a lot more power :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/628>,
or mute the thread
