### ISSUE TITLE
More Privacy + Content Controls For User & Admin Please?

### ISSUE THREAD

**Issue by simyas** [PHPfox-Official/phpfox-v4-feature-requests#652]
In general, Social Engine (SE) has more extensive Privacy Controls that are pretty good to use/have.  Can we add:

- In **"Post Something..." box** on timeline Dashboard, a more extensive list of post restrictions similar to SE.  They allow you to post to regions like Africa or N. America in addition to your normal settings.

- In **"Photos" module**, privacy control is ok, but SE has added controls like "Comment Privacy (who may comment on photos)" & "Tagging (who may tag this photos)" <-- all very helpful across other Modules as well (i.e. Events, Music, Blogs, etc).

- In **"Blogs" module**, add "Status (dropdown)" to select if Blog is published or draft, also add more Privacy controls described in Photos ^.  Incorporating a field for tags would be nice too.

- In **"Events" module**, would be nice to control/designate Host, also add more privacy controls like I mentioned in Photos module.  Also add "Who May Upload Photos" to events module controls.

- From **"Admin" CP**, SE has a good ability to broadcast announcements or make changes by designated regions.  Would be nice to control which audience you are communicating with...on both the User and Admin end.

- We also need more detailed **Filtered Search** controls (like you have for Members or Forums) for Events, Albums, Marketplace, Pages, Groups, Videos, Music.  Again, SE has a good example of this.

- Need to be able to **Flag comments** everywhere, not just on dashboard.

- Nice to have Admin of **Forum Topics** shown

- **Account Settings** controls could be more extensive and specific:  need custom profile address (i.e. phpfox.com/username), decide what's published in recent activity feed or admin featured sections, Network options, etc.  Again, SE has REALLY good and extensive privacy/content controls.  I highly suggest incorporating more specific ones.

**Comment by Elshara** [comment]
Basically, this can already be done. All you need to do is enable a
custom privacy settingand then add options to it.
The username can be changed in account settings if you turn off set
connection using profile ID in member gesitration settings.
All the settings you're looking for exist on a per user group basis in
PHPFox already.
I know this is possible for a fact because in my experience as someone
who has been with Social Engine exclusively 2013 - 2018, and, as
someone who has recently switched to PHPFOX, the opposite is generally
true.
Whilst Social Engine claims to deliver on a lot of key issues, one of
the most troubling things I find about that script, is that not only
has it become a walled garden, but PHPFOX has done more for security
and account settings, than Social Engine ever has.
Sure, some things on PHPFOX could use some work, but nothing you've
mentioned here is undoable in PHPFOX. as a matter of fact, to be able
to achieve posting to certain countries only, enable friends mode and
then just add your friends who you know are from X countries. If you
want to share with other friends, you can. But make a list of the
friends in each country, then only share to that list. Boonex Dolphin
has implemented this functionality really well.
