### ISSUE TITLE
Short video "stories"

### ISSUE THREAD

**Issue by nativedragon11** [PHPfox-Official/phpfox-v4-feature-requests#677]
A lot of site members want the ability to upload a "story" which is basically a short video that displays for only 24 hours on their profile, and in the site's "stories" section before deleting itself. 

The option to set the story length limit (example: 1 minute), the expiration time (example: 24 hours) and usergroup settings to enable/disable for different groups, would be great.

This could be a core app, or a separate app. Either way, with the function available on the big networks, site members will be looking/asking for it on our sites too!

**Comment by spirogg** [comment]
Great Idea, kinda like SnapChat very nice if we can get this.
 when select to add video story - it should only give user the option to use video option to record only so to create a story and video recording will end at the time limit we set 30 sec, 1 min, 2 min. 

if we use upload video it will not allow to set time limit and so it maybe longer than our selected time limit - so the user video will fail to upload.

very nice plugin to have : 

we could use marketplace app since it has expiration and video app together in a different plugin with time limit and expiration limit ??

Spiro

**Comment by dawn2323** [comment]
Very nice suggestion!
