### ISSUE TITLE
can we give admin rights for groups to registered user and not allow to create groups?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-feature-requests#718]
is there a way to allow a registered user to be an admin of a group, but at the same time not allow registered user to create a new group, just be admin of a group and only edit the group or groups they are admins of ??

right now If we turn off to not allow to create a group for registered users they cannot manage the group they are admins of ?

thanks hope this is possible

Spiro

**Comment by PhpFoxJohnJr** [comment]
Thank you Spirogg for taking the time to request this...we really do need this for pages and groups.

**Comment by harrison05** [comment]
Duplicate of #713

**Comment by PhpFoxJohnJr** [comment]
Harrison05, please explain how this is a duplicate to the other request.  This is a very simple idea that you guys have incorporated in Blog, Events...etc.  There should be two settings instead of the one you currently have.  Those setting are the ability to add a group and the second setting is the ability to edit group.  I don't see you did this for the other modules but forgot Pages and Groups.  So unless I give everyone in a user group permission to add groups (which could be hundreds or thousands)...they are not able to edit the group I transferred to them (which may only be a handful).  You need to make two settings.

**Comment by PhpFoxJohnJr** [comment]
Here is the two settings for blogs in case you are confused with my long-winded explanation.
BLOGS USER GROUP SETTINGS:
Can edit their own blogs?
Can add a new blog?

GROUPS USER GROUP SETTINGS:
Can add groups?
Although you do have Can edit all groups? but you forgot Can edit their own Group?

**Comment by harrison05** [comment]
@PhpFoxJohnJr Oh sorry, my mistake.

> right now If we turn off to not allow to create a group for registered users they cannot manage the group they are admins of ?

@spirogg This is a bug of Groups App. Can you help me create an issue for this in repo https://github.com/PHPfox-Official/phpfox-v4-issues, we will check and fix it, then close this issue.

Thanks.

**Comment by PhpFoxJohnJr** [comment]
The group apps as well as the page app as well...though it was nice in this last upgrade you added the menu item Reassign owner but now make this even more important if you reassign to a group who currently does not right to add groups or page...it doesn't work the can't do anything.  Also just for my info...the new feature reassign group...does that change the founder in the database?

**Comment by spirogg** [comment]
@PhpFoxJohnJr 
Created repo here #2397 for pages and groups closing this now
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2397
