### ISSUE TITLE
[v4.2.0] Search button not working

### ISSUE THREAD

**Issue by DonnaScriptTechs** [PHPfox-Official/phpfox-v4-feature-requests#8]
_From @Spaninet on February 1, 2016 14:56_

The search button is not working in v4.2.0.

_Copied from original issue: moxi9/phpfox#1052_

**Comment by Data66PF** [comment]
Please always provide details when testing. What browser and OS? did you test the demo site?

**Comment by Data66PF** [comment]
_From @Spaninet on February 1, 2016 15:36_

Tested with Firefox 44 for Windows in:

- My dev site
- http://v4.phpfox.com/
- http://stage.phpfox.com/

**Comment by Data66PF** [comment]
_From @Spaninet on February 1, 2016 15:42_

Tested also with Internet Explorer 11.

**Comment by Data66PF** [comment]
_From @neil96 on February 1, 2016 16:15_

That's just icon, not a button. We will discuss with team and consider change it to button.

**Comment by Data66PF** [comment]
_From @Spaninet on February 1, 2016 16:21_

Ok.

**Comment by PhpFoxJohnJr** [comment]
This is not an interest or an enhancement.  There is no excuse for this as you spent more time thinking about it then it takes fixing it.  It would take less than 5 minutes to add a real button that calls the same exact process that it calls when you hit enter...come on people what do you think were stupid.  This is the on the Main page where every person who used this software as a owner or user has tried it once thinking...what that is going on.  So should I expect going over any of the coders house that when I walk up to the front door and attempt to go in find out....oh that is not a real door that is an "icon" of a door.  Data you need to move this to a bug as that is what it is and it looks like it has been going on since 4.2.  I will set up a poll to show how dumb this is.  Sorry to be pain but I have seen a couple of the coders here fix things in 13 minutes that I would have expected to take at least an hour or more so I know they have the talent.

**Comment by Data66PF** [comment]
Our core developer Neil said it is working as it was designed and needs to be a feature request. No need for the unnecessary comments in your post. It is marked Interest so we can look at improving this once we get the Major issue of our v4.4 optimizations and security overhaul done which is far more important right now. We have to prioritize and this is not as pressing as the optimizations and security audit we are working on right now.

**Comment by PhpFoxJohnJr** [comment]
I totally understand...and you are right this is the least of the problems and probably should be done last.  Not in any of my bug reports did I say it has to be done now...next week or even next month.  I know they are busy...they have done outstanding job in my point of view.  I just don't like issues rephrased as working as intended because that is not true.  Maybe I don't understand the concept behind enhancement and interest category...sorry.

Well I guess I need to open my eyes... as you stated it to me " It is marked Interest so we can look at improving this once we get the Major issue "  Which makes perfect sense...

**Comment by Data66PF** [comment]
Yes, the labels here in the feature system are different. When in the bug tracker, if the script was designed a specific way, and if the issue reported is asking to change how a feature is designed, it is deemed an Enhancement and move to feature requests now.

Once in feature requests, it is already considered an Enhancement so that label is not needed. We then determine if we Reject it, are Interested in making it, Accept it or Implement it, among a few other labels. Before it can be Accepted, it first has to have Interest in making it. Then it goes the next step of being Accepted or not.

**Comment by PhpFoxJohnJr** [comment]
Thanks neil96 for taking this on.

**Comment by PhpFoxJohnJr** [comment]
Thank you Neil for fixing this small issue as it drove me crazy for so long :)
