### ISSUE TITLE
Keep "Settings" submenu open after clicking on it in admincp

### ISSUE THREAD

**Issue by darksolar1** [PHPfox-Official/phpfox-v4-feature-requests#82]
I find that it gets really annoying to have to keep clicking settings and to open the submenu and then clicking on the submenu and then it closing as the page load only to do it many many more times. It literally feels like you're going 3 steps back to move 1 step forward.

It would save a lot of mouse clicks and make it much more convenient if the submenu stays open as it loads the appropriate page.

**Comment by Data66PF** [comment]
It closes the submenus in order to show the settings. Otherwise, the submenu overlaps the settings and it would be a smaller display of the settings. I am not in favor of this even though it does take more work to get to a submenu, I prefer to be able to see the settings without issue. Many use small screens (such as laptops) and making that area even smaller would be detrimental.

**Comment by lueung** [comment]
Not being able to see all thing is not an issue with a scroll bar at the bottom. 99%of the stuff on the admin pages don't take up the entire screen width anyway.

I myself use a laptop with a 12" screen as my main work computer so I see no issue with this. This will certainly make managing the site much easier and not detrimental at all.

**Comment by neil96** [comment]
Dear @darksolar1 ,

This feature is now available on phpFox 4.6.0.

Regards.
